DROP TABLE IF EXISTS practica1.tmp_country_codes;
DROP TABLE IF EXISTS practica1.tmp_geonames;
DROP TABLE IF EXISTS practica1.tmp_level_1a;
DROP TABLE IF EXISTS practica1.tmp_locations;
DROP TABLE IF EXISTS practica1.tmp_projects;
DROP TABLE IF EXISTS practica1.tmp_transactions;

DROP TABLE IF EXISTS practica1.TRANSACTION;
DROP TABLE IF EXISTS practica1.CURRENCY;
DROP TABLE IF EXISTS practica1.LEVEL_1A;
DROP TABLE IF EXISTS practica1.PROJECT;
DROP TABLE IF EXISTS practica1.TYPE_STATUS;
DROP TABLE IF EXISTS practica1.COUNTRY_CODES;
DROP TABLE IF EXISTS practica1.GEONAME;
DROP TABLE IF EXISTS practica1.LOCATION;
